fragment ScrapperRunScrapper on Scrapper {
  id
  name
  steps {
    id
  }
}

query GetMyScrapperRun($id: ID!) {
  getMyScrapperRun(id: $id) {
    id
    createdAt
    endedAt
    name
    scrapper {
      ...ScrapperRunScrapper
    }
    error {
      date
      message
      name
      stepId
    }
    steps {
      ...ScrapperBuilderStep
    }
    state
    error {
      date
      message
      name
    }
    keyPairValues
    results {
      id
      endedAt
      startedAt
      state
      performance {
        duration
      }
      step {
        ...ScrapperBuilderStep
      }
      screenshots {
        ...FileLinkFile
      }
      error {
        date
        message
        name
      }
      values {
        id
        screenshot {
          ...FileLinkFile
        }
        sourceElement {
          id
          classNames
          tag
        }
        value
      }
    }
  }
}
