version: '3.4'

services:
  api:
    networks:
      - app
    command: [sh, -c, "node apps/api/src/main.js"]
    environment:
      APP_NAME: scrapper-gate
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: app-postgres
      DB_PORT: 5432
      DB_NAME: app
      HASH_ROUNDS: 10
      JWT_SECRET: SECRET
      NODE_ENV: development
      MAIL_USER: przemyslawzydek@gmail.com
      MAIL_PASS: drpkguyoyjoqoprt
      SITE_EMAIL: przemyslawzydek@gmail.com
      SERVER_URL: http://localhost:5000
      SITE_URL: http://localhost:3000
      SECURITY_PORT: 50050
      SECURITY_HOST: security
      SECURITY_API_KEY: b6cfcd8f-db8e-2cb5-cb34-e1a8900067fd
      AWS_REGION : eu-west-1
      AWS_ACCOUNT_ID : root
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SQS_ENDPOINT_URL: http://localstack:4566
      AWS_SQS_SCRAPPER_CHROMIUM_QUEUE_URL: http://localstack:4566/000000000000/development-scrapper-chromium.fifo
      AWS_SQS_SCRAPPER_WEBKIT_QUEUE_URL: http://localstack:4566/000000000000/development-scrapper-webkit.fifo
      AWS_SQS_SCRAPPER_MOZILLA_QUEUE_URL: http://localstack:4566/000000000000/development-scrapper-mozilla.fifo
      AWS_SQS_MESSAGE_TEST_QUEUE_URL: http://localstack:4566/000000000000/development-message-queue-test.fifo
      AWS_SQS_API_VERSION: 2012-11-05
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IGNORED_BROWSER_TYPES: Firefox,Safari
      TS_NODE_TRANSPILE_ONLY: true
    build:
      context: .
      dockerfile: apps/api/docker/Dockerfile
    ports:
      - 3000:3000

networks:
  app:
