module.exports = {
  projects: [
    '<rootDir>/apps/browser-extension/popup',
    '<rootDir>/apps/api',
    '<rootDir>/libs/shared/routing',
    '<rootDir>/libs/shared',
    '<rootDir>/libs/shared/common',
    '<rootDir>/libs/shared/logger',
    '<rootDir>/libs/shared-backend/awilix',
    '<rootDir>/libs/shared-backend/server',
    '<rootDir>/libs/shared-backend/unit-of-work',
    '<rootDir>/libs/shared-backend/cqrs',
    '<rootDir>/libs/shared-backend/database',
    '<rootDir>/libs/shared-frontend/common',
    '<rootDir>/libs/shared/domain/auth',
    '<rootDir>/libs/shared-frontend/schema',
    '<rootDir>/libs/shared-frontend/auth',
    '<rootDir>/libs/shared-frontend/theme',
  ],
};
