org: theunderscorer
app: scrapper-gate
service: scrapper-gate-lambdas

frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  test:
    handler: apps/lambdas/src/functions/test.test
    events:
      - http:
          method: get
          path: test
          integration: lambda

custom:
  webpack:
    webpackConfig: apps/lambdas/webpack.config.js
