export * from './AppError';
export * from './HttpError';
export * from './user/EmailAlreadyTakenError';
export * from './UnauthorizedError';
export * from './html/InvalidSelectorProvidedError';
export * from './scrapper/ScrapperNotFoundError';
export * from './scrapper/ScrapperRunError';
export * from './browserExtension/NoActiveTabFoundError';
export * from './scrapper/ScrapperAlreadyRunningError';
