mutation UpdateScrapper($input: ScrapperInput!) {
  updateScrapper(input: $input) {
    ...ScrapperBuilderScrapper
  }
}

fragment ScrapperBuilderScrapper on Scrapper {
  id
  createdAt
  isRunning
  name
  updatedAt
  type
  startNodePosition {
    x
    y
  }
  lastRun {
    id
    endedAt
    state
  }
  steps {
    ...ScrapperBuilderStep
  }
  runSettings {
    dialogBehaviour
    initialUrl
    noElementsFoundBehavior
    timeoutMs
    promptText
  }
  variables {
    id
    createdAt
    defaultValue
    updatedAt
    isBuiltIn
    key
    scope
    type
    value
  }
}

fragment ScrapperBuilderStep on ScrapperStep {
  id
  action
  key
  createdAt
  updatedAt
  mouseButton
  fullPageScreenshot
  isFirst
  navigateToUrl
  nextStep {
    id
  }
  previousSteps {
    id
  }
  stepOnTrue {
    id
  }
  stepOnFalse {
    id
  }
  reloadDelay
  selectors {
    type
    value
  }
  waitIntervalCheck {
    ...FullDuration
  }
  waitIntervalTimeout {
    ...FullDuration
  }
  valueType
  url
  typeDelay
  useUrlFromPreviousStep
  attributeToRead
  waitDuration {
    ...FullDuration
  }
  waitType
  newRunSettings {
    dialogBehaviour
    noElementsFoundBehavior
    promptText
  }
  position {
    x
    y
  }
  conditionalRules {
    id
    type
    rules {
      id
      meta
      type
      value
      what
      whatValue
      when
    }
  }
}
