mutation UpdateScrapper($input: ScrapperInput!) {
  updateScrapper(input: $input) {
    id
    name
    isRunning
    lastRun {
      id
      endedAt
      state
    }
    type
    steps {
      ...ScrapperBuilderStep
    }
  }
}

fragment ScrapperBuilderStep on ScrapperStep {
  id
  action
  key
  createdAt
  updatedAt
  mouseButton
  navigateToUrl
  nextStep {
    id
  }
  previousSteps {
    id
  }
  stepOnTrue {
    id
  }
  stepOnFalse {
    id
  }
  reloadDelay
  selectors {
    type
    value
  }
  url
  typeDelay
  useUrlFromPreviousStep
  position {
    x
    y
  }
  conditionalRules {
    id
    type
    rules {
      id
      meta
      type
      value
      what
      whatValue
      when
    }
  }
}
