mutation SendScrapperToQueue($input: StartScrapperInput!) {
  sendScrapperToRunnerQueue(input: $input) {
    scrapper {
      id
      name
      lastRun {
        id
        endedAt
        state
      }
    }
    run {
      id
      endedAt
      state
    }
  }
}

query GetScrapperState($id: ID!) {
  getMyScrapper(id: $id) {
    id
    name
    lastRun {
      id
      endedAt
      state
    }
  }
}
