mutation SendScrapperToQueue($input: StartScrapperInput!) {
  sendScrapperToRunnerQueue(input: $input) {
    scrapper {
      ...ScrapperForRun
    }
    run {
      id
      endedAt
      state
    }
  }
}

query GetScrapperState($id: ID!) {
  getMyScrapper(id: $id) {
    ...ScrapperForRun
  }
}

fragment ScrapperForRun on Scrapper {
  id
  isRunning
  name
  type
  steps {
    id
  }
  lastRun {
    id
    endedAt
    state
  }
  runSettings {
    dialogBehaviour
    initialUrl
    noElementsFoundBehavior
    timeoutMs
    promptText
  }
}
