query GetScrapperForBuilder($id: ID!) {
  getMyScrapper(id: $id) {
    id
    createdAt
    isRunning
    name
    state
    updatedAt
    type
    lastRun {
      id
      endedAt
    }
    steps {
      ...ScrapperBuilderStep
    }
    runSettings {
      dialogBehaviour
      initialUrl
      noElementsFoundBehavior
      timeoutMs
    }
    variables {
      id
      createdAt
      defaultValue
      updatedAt
      isBuiltIn
      key
      scope
      type
      value
    }
  }
}
