query GetScrapperForBuilder($id: ID!) {
  getMyScrapper(id: $id) {
    id
    createdAt
    isRunning
    name
    state
    updatedAt
    type
    steps {
      ...ScrapperBuilderStep
    }
    variables {
      id
      createdAt
      defaultValue
      updatedAt
      isBuiltIn
      key
      scope
      type
      value
    }
  }
}
