name: Tests
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npx nx build browser-extension --prod && npx nx build api --prod

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 13.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 13.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Test
        run: npm run test


